version: '3.8'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.2.4
    container_name: keycloak-overscore
    ports:
      - "8080:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HEALTH_ENABLED: true
      KC_METRICS_ENABLED: true
    volumes:
      - ./themes/overscore:/opt/keycloak/themes/overscore
    command: start-dev
    restart: unless-stopped
    networks:
      - keycloak-network

networks:
  keycloak-network:
    driver: bridge 